language: node_js
node_js:
  - "node"

cache: npm

script: npm run build --legacy-peer-deps

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
on:
  branch: master
