language: node_js
node_js:
  - "node"

cache: npm

install: npm install --legacy-peer-deps

script: npm run build

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
on:
  branch: master
